#!/bin/bash
#SBATCH --job-name='job32fa982104400ed350b0bc5566559b48'
#SBATCH --output='/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/registry-2021-10-26/logs/job32fa982104400ed350b0bc5566559b48.log_%a'
#SBATCH --error='/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/registry-2021-10-26/logs/job32fa982104400ed350b0bc5566559b48.log_%a'
#SBATCH --time=2880
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000


#SBATCH --array=1-216
export DEBUGME=
Rscript -e 'batchtools::doJobCollection("/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/registry-2021-10-26/jobs/job32fa982104400ed350b0bc5566559b48.rds")'
