#!/bin/bash
#SBATCH --job-name='job046979e9644dc6189549877c4e32a855'
#SBATCH --output='/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/registry-2021-10-05/logs/job046979e9644dc6189549877c4e32a855.log_%a'
#SBATCH --error='/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/registry-2021-10-05/logs/job046979e9644dc6189549877c4e32a855.log_%a'
#SBATCH --time=2880
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000


#SBATCH --array=1-216
export DEBUGME=
Rscript -e 'batchtools::doJobCollection("/projects/genomic-ml/sub-quadratic-full-gradient-AUC-optimization/app/registry-2021-10-05/jobs/job046979e9644dc6189549877c4e32a855.rds")'
